### ISSUE TITLE
Установка фотохоста

### ISSUE THREAD

**Issue by lapons** [vla7/akina#100]
Подскажите полуйста, немного не понятен 2 пункт из инструкции установки.
2. Установить владельцем файлов www-data (или ваш владелец процесса Apache) и права 755, или права 777, если вы не знаете что такое Apache
Сколько раз перечитывал никак не могу понять. Тут нет ошибки, например в склонении или в описании?
Тое-сть владельцем всех файлов надо сделать  кого-то по имени "www-data"?
Или тому кто является владельцем "www-data" надо дать комуто какие-то права?
Или кого надо установить владельцем "www-data" ?
Если опустить скобки, то предложение получается каким-то незаконченыным, какбудто из него вырвали слова.
Вообщем люди добрые подскажите как мне его установить, у меня VDS+ISPManager? Подскажите это как-нибудь можно сделать через ISPManager.
Раншеь скрипт работал нормально, потом переехал с виртуального на VDS и начались проблемы. Много проблем помогло решить дав на все папки в корне права 777 (хотя в нутри этих папок другие папки почему-то имеют права 755, так и должно быть?)
А на файлы в корне какие должны быть права? У меня на них стоят права 644

**Comment by TerVel76** [comment]
Читать нужно так:
- если можете установить владельцем файлов и каталогов www-data - тогда установить права 755...
- а если не можете, тогда 777

Про 644 на файлы в корне - правильно.

**Comment by TerVel76** [comment]
А про скобки - не на всех серверах www-data является владельцем сервиса APACHE

**Comment by lapons** [comment]
То-есть надо сначала создать пользователя "www-data", а потом установить его владельцем файлов и каталогов фотохостинга?

**Comment by lapons** [comment]
И что лучше, чтоб владельцем файлов и каталогов был "www-data" или пользователь?

**Comment by lapons** [comment]
После переезда на VDS в сентябре у меня почему-то создаются папки и файлы под какимто пользователем "48" Хотя я такого пользователя не создавал. 
вот скриншот http://i70.fastpic.ru/big/2015/0927/2e/85d1f5a71a7f165c4adc436454c1c42e.jpg
Подскажите где собака зарыта?

**Comment by TerVel76** [comment]
"И можно-ли это вообще сделать через ISPManager?" - без понятия

" у меня почему-то создаются папки и файлы под какимто пользователем "48" Хотя я такого пользователя не создавал." - это и есть www-data

**Comment by lapons** [comment]
Кто знает подскажите пожалуйста как сделать чтобы веб сервер запускался от имени пользователя, а не от www-data и т.п. ? куда примерно копать? 
ОС: CentOS

**Comment by vla7** [comment]
>И можно-ли это вообще сделать через ISPManager?
Можно просто залить движок через ISPManager или FTP - пользователь выставится автоматически. Если все работает - ничего менять НЕ НУЖНО. Если не работает - нужно выставить права. На папки 755, на файлы - 644.

**Comment by lapons** [comment]
У меня при загрузке фоток на фотохостиг через веб форму владельцем и пользователем автоматически становится апач. 
Однако с правами на папки 755 не загружает фотки на фотохост, пишет нету прав на запись, а вот если сменить права на папки на 777 , то всё работает нормально.
/working - тоже дал права 777
А вот файла /working/cachefile.dat у меня почему-то вообще нету. (версия скрипта 1.0.8)

**Comment by vla7** [comment]
Если приходится ставить 777 - значит владелец файлов скрипта отличается от юзера, от имени которого работает апач. Апач работает в режиме CGI?

**Comment by lapons** [comment]
С FastCGI у меня вообще не заработало, даже если на все папки права 777. Вернул обратно Режим работы PHP как модуль апач и всё заработало. Вернул права на папки с 777 на 755 и перестало работать, стало писать нет прав на запись. Вернул опять права с 755 на 777 и всё заработало. 
Если посмотреть через ISPManager кому принадлежат сегодняшние папки и файлы в img и thumbs, то пишет "Владелец Apache" | Группа Apache.
Но если посмотреть через FTP-клиент, то показывает в столбце владелец "48"
Ну да бох с ним, заработало и нормально. Просто на VDS стоит CentOS 7. А это совсем новая система и может её ещё хостеры не научились нормально настраивать, да и может баги в ней ещё присутствуют. Даже FTP не может в пасивном режиме работать, а только в активном, что только я не делал.

**Comment by lapons** [comment]
А можно-ли как-нибудь добавить затемнённое всплывающее окно проверки возраста перед просмотром полной версии фотографии? Типа "Вам есть 18 или нет 18"
И при нажатии на "Нет 18" происходило перенаправление например на диснейленд. Да и что-бы не спрашивало каждый раз, было-бы хорошо записать это в куки с жизнью в 1 сутки.

**Comment by TerVel76** [comment]
- Если посмотреть через ISPManager кому принадлежат сегодняшние папки и файлы в img и thumbs, то пишет "Владелец Apache" | Группа Apache.
- Но если посмотреть через FTP-клиент, то показывает в столбце владелец "48"

Все правильно, в *nix системах (кстати как и в Windows) пользователи и группы задаются числом.
Просто в вашем FTP клиенте не включен (или не поддерживается) отображение владельца в текстовом виде.

**Comment by vla7** [comment]
Как я писал выше, если заливать через FTP или ISPManager - владелец ставится автоматически, ничего менять НЕ НАДО, http://i70.fastpic.ru/big/2015/0927/2e/85d1f5a71a7f165c4adc436454c1c42e.jpg не надо ставить Apache, надо было оставить lapons и все бы отлично работало с 755

**Comment by lapons** [comment]
Да, при заливке через FTP владелец автоматически поставился "lapons"
Но при загрузке через скрипт фотохостинга пладельцем автоматически ставиться Apache.
Вот я и забил тревогу, мол вдруг я потом опять решу переезжать например на выделенный сервер, а у меня половина папок и файлов будут с владельцем "lapons", а другая с владельцем "Apache" и какая-то половина фоток отвалится. А оказывается, что при загрузки бекапа-фотохостинга через FTP на все папки и файлы автоматически поставится владелец "lapons", а уж только на новые файлы и папки создаваемые скриптом может быть другой владелец. Да ну и фиг с ним, ведь всёравно всё будет работать :)
