### ISSUE TITLE
Как прикрутить рекламу

### ISSUE THREAD

**Issue by Bender19** [vla7/akina#102]
Здравствуйте! Как прикрутить рекламу чтоб скрипт рекламы работал не на главной странице а именно на странице просмотра. Уже все перепробывал никак не выходит

**Comment by vla7** [comment]
В index.php перед
echo parse_template(get_template('index'), $parse_main);
вставляем:
if(isset($_GET['v'])) //если страница просмотра
{
    $parse_main['{ad1}']="html-код баннера";
}

В шаблоне вставляем {ad1} в место, где хотим отображать баннер.

По результатам отпишитесь, пожалуйста.

**Comment by Bender19** [comment]
Здравствуйте! Спасибо за ответ.Но я дал не совсем ту информацию..мне нужен не баннер а реклама типа попандер или кликандер. Дапустим я разместил на сайте картинку ( превью увеличение по клику) и чтобы ее посмотреть человек кликает на картинку и уже попадает на страницу просмотра полного изображения и вот тут кликнув по любому месту страницы должен срабатывать скрипт попандера. И вот тут уже мне непонятно куда внедрять код.На главной все работает а там где надо нет.Сам скрипт фотохостинга просто замечательный но вот такая беда.

**Comment by vla7** [comment]
Код для вставки остается стандартным.
А вот сам вставляемый код уже пишите под свои нужды, события и т.д, это уже совсем другая история.

**Comment by Bender19** [comment]
Понятно! Попробую.

**Comment by Bender19** [comment]
Попробывал! Вставил код сайт перестал работать внутренняя ошибка сервера. Удалил код заработал
