### ISSUE TITLE
BB Code/ HTML Code All images

### ISSUE THREAD

**Issue by CtrlSystem** [vla7/akina#103]
When use Multi upload form its only available BB Codes and HTML Codes All images. Do you can tell me, please how to add and the other 2 Types (Link Images Codes/ Direct Link Images Codes All images ).

Regards,
CtrlSystem

**Comment by vla7** [comment]
Patch is ready but not in master brunch yet.
Please, wait - I have contacted the author already. If he will not add it - I will write it itself.

**Comment by sal3** [comment]
@CtrlSystem 
I have added "Direct links to all images" when multiupload: view.php and view_summary.tpl in all templates. Wait for commit.

**Comment by vla7** [comment]
Merged to Master.

**Comment by sal3** [comment]
Also added "Links to image pages" when multiupload.
