### ISSUE TITLE
Проблема: тёмная полоса на фото при уменьшении размера

### ISSUE THREAD

**Issue by MihaylovRA** [vla7/akina#104]
Здравствуйте! 

Уважаемый разработчик, помогите пожалуйста решить проблему.

Появляется тёмная полоса на фото при уменьшении размера во время загрузки.

Пример:
http://fotohosting.info/?v=2015-11-04_xsqicm085qdm8qfbwn0ki7q3l.jpg
http://fotohosting.info/?v=2015-11-04_licqevufxn64hsgi469xbhs4g.jpg

В чём может быть дело?

**Comment by vla7** [comment]
Ошибка найдена и исправлена. Рекомендую обновиться: https://github.com/vla7/akina/archive/master.zip

**Comment by MihaylovRA** [comment]
Спасибо! А в какие файлы вносились изменения? Подскажите пожалуйста.

**Comment by vla7** [comment]
В файл functions.php
