### ISSUE TITLE
Lighttpd

### ISSUE THREAD

**Issue by aloneuser** [vla7/akina#112]
Lighttpd не обрабатывает ссылки вида 
http://images.libreportal.net/?v=2016-03-14_r4opbgcbp8tfh2hb4r6zyjz4q.jpg

Вот настройки сервера lighttpd:
`$HTTP["host"] =~ "(^|\.)images.libreportal\.net$" {
server.document-root = "/var/www/images.libreportal.net"
accesslog.filename = "/home/aaa/libreportal/access.log"
server.errorlog = "/home/aaa/libreportal/error.log"
url.rewrite-once = ( "^/$" => "/","^/index.php/$" => "/index.php?",)
url.rewrite-if-not-file = ( "^/(.*)" => "/index.php?_route_=$1" )
}
`
Как переделать строку запроса что обрабатывались урлы начинающиеся с ?v=   ?

**Comment by TerVel76** [comment]
C Lighttpd не работал, но могу предположить что:
`url.rewrite-if-not-file = ( "^/(.*)" => "/index.php?_route_=$1" ) }`
нужно написать как:
`url.rewrite-if-not-file = ( "^/(.*)" => "/index.php?$1" ) }`

**Comment by aloneuser** [comment]
Получилось:
```
#url.rewrite-once = ( "^/$" => "/","^/?/$" => "/view.php?",)
url.rewrite-if-not-file = ( "?v=" => "/index.php?$1" ) 
```
Но это правило работает только для поддоменов, а правило:
`url.rewrite-if-not-file = ( "/images/?v=" => "/images/index.php?$1" ) `
никак не хочет работать, показывает 404:
`http://libreportal.net/images/?v=2016-03-14_r4opbgcbp8tfh2hb4r6zyjz4q.jpg`

**Comment by aloneuser** [comment]
Даже так не работает:

`url.redirect = ( "/images/?v=" => "/images/index.php?$1")`

**Comment by aloneuser** [comment]
А как добавить index.php в вывод url : /images/index.php?v=2016-03-14_r4opbgcbp8tfh2hb4r6zyjz4q.jpg

**Comment by TerVel76** [comment]
Какая версия Akina ?

**Comment by TerVel76** [comment]
https://github.com/vla7/akina/blob/master/functions.php#L318
https://github.com/vla7/akina/blob/master/functions.php#L329
https://github.com/vla7/akina/blob/master/functions.php#L330

**Comment by aloneuser** [comment]
Спасибо!
Получилось!
