### ISSUE TITLE
Как сделать так, чтобы превью картинок были в JPG?

### ISSUE THREAD

**Issue by ivandubskoj** [vla7/akina#113]
Здравствуйте!
По умолчанию, загруженное изображение остаётся в том же формате, что и было изначально.

Подскажите, пожалуйста, а как сделать так чтобы превью было в формате JPG, а при нажатии на него уже перекидывало на страницу с оригинальным форматом. Т.е. например, залил картинку в PNG - превью на него в JPG, было, а полноразмерная картинка в PNG без изменений?

Спасибо. Проект просто отличный!

**Comment by TerVel76** [comment]
99 строка https://github.com/vla7/akina/blob/master/functions.php
$save = $image->save();
замените на 
$save = $image->save('jpg');

**Comment by ruslanishe** [comment]
да вот тоже самое у  меня   только я меня в файле  **functions.php** не чего  не меняет.

**Comment by ivandubskoj** [comment]
А как правильнее?

2017-09-09 11:36 GMT+04:00 ruslanishe <notifications@github.com>:

**Comment by ruslanishe** [comment]
не знаю  как правильно.   если есть  возможность  подскажите?
