### ISSUE TITLE
Проблема

### ISSUE THREAD

**Issue by AndrewRAN** [vla7/akina#114]
Мне пишет
**Warning: Missing argument 5 for resize(), called in D:\XAMPP\htdocs\functions.php on line 274 and defined in D:\XAMPP\htdocs\functions.php on line 14**, когда я ставлю галку на "Уменьшение изображения"
и
**Fatal error: Class 'finfo' not found in D:\XAMPP\htdocs\gdenhancer\models\Library.php on line 27**, когда ставлю галочку на "Создать превью"

**Comment by TerVel76** [comment]
Class 'finfo' not found in D:\XAMPP\htdocs\gdenhancer\models\Library.php
у вас не установлена библиотека fileinfo для PHP 
http://php.net/manual/ru/class.finfo.php

**Comment by AndrewRAN** [comment]
Спасибо, с превью проблему решил. Изображение тоже уменьшается нормально, но сверху вылазит ошибка **Warning: Missing argument 5 for resize(), called in D:\XAMPP\htdocs\functions.php on line 274 and defined in D:\XAMPP\htdocs\functions.php on line 14**

**Comment by TerVel76** [comment]
Никак.
5-я переменная в функции не задействована.

Похоже на ошибку в коде.

**Comment by AndrewRAN** [comment]
И что мне теперь делать?

**Comment by TerVel76** [comment]
Либо игнорировать.
Либо подправить , заменить 14 строку functions.php
 function resize($filename, $resize_width, $resize_height, $texttype=false, $filename_src)
на 
function resize($filename, $resize_width, $resize_height, $texttype=false)
