### ISSUE TITLE
Предлагаю добавить полосу загрузки

### ISSUE THREAD

**Issue by AndrewRAN** [vla7/akina#115]
Здравствуйте. Пишу, потому что сам столкнулся с этим. По виду узнал, что это именно ваш скрипт, загружаю 20 гифок. Все весят по 5 МБ. Начал загрузку. Интернет у меня медленный, Прошло где-то 15 секунд, я всё жду и жду. Потом взял и закрыл вкладку, психанув. И только после третьей попытки я понял, что внизу слева показывается "Загрузка (%)" (у меня Google Chrome). Чтобы не было людей, натыкавшихся на мои грабли, предлагаю добавить эту функцию, либо сделать дополнение.

**Comment by ivandubskoj** [comment]
Присоединяюсь, сделайте, пожалуйста, хотя бы простенький индикатор процесса (прогресс-бар), либо "полоской", либо процентами. Спасибо.
