### ISSUE TITLE
Периодическая проблема с загрузкой изображений из Интернета (загрузить по ссылке) - Неверный MIME-тип

### ISSUE THREAD

**Issue by ivandubskoj** [vla7/akina#116]
Здравствуйте! Если загружать из Интернета (загрузить по ссылке), очень часто выскакивает такое сообщение:

> Ошибка!
> Изображение не загружено. Ошибка: Неверный MIME-тип изображения, допускаются image/gif, image/pjpeg, image/jpeg, image/png, image/bmp, image/x-ms-bmp. Вы пытались залить n/a

Хотя файлы нормальные в формате JPG! А если, например сохранить эту картинку на компьютер и с компьютера попробовать загрузить - всё в порядке.

Вот пример (НЕ СОЧТИТЕ ЗА СПАМ, ПОЖАЛУЙСТА!):

http://imageportal.ru/wallpapers/1211/tropicheskie-oboi-na-rabochiy-stol.jpg

На другие фотохостинги (не на вашем скрипте), картинка по этой ссылке загружается на фотохостинг, а с вашим скриптом, что-то не так....

Также если эту картинку сохранить на компьютер, а потом с компьютера загрузить на фотохостинг - всё нормально, а вот по ссылке сразу, почему-то нет и дело даже не в разрешении картинки пробовал и 640, без разницы.

Также столкнулся с такой проблемой, что если вставить прямую ссылку загруженной картинки, на свой же фотохостинг, он почему-то тоже её НЕ принимает и выскакивает эта же ошибка.

Подскажите, пожалуйста, что делать?

**Comment by vla7** [comment]
Вопрос закрыт по сроку давности.
