### ISSUE TITLE
Не работает на HTTPS

### ISSUE THREAD

**Issue by abr307** [vla7/akina#117]
Долгое время пользовался этим скриптом, но после того как перевел сайт на https кнопка добавить картинку перестала работать. Как решить проблему?

**Comment by unencoded** [comment]
Сегодня впервые устанавливал этот скрипт на домен с https, столкнулся с тем, что стили не подгружались.
Решилось довольно просто.
На 46 строчке файле config.php изменил строчку
с 
`$config['site_url']='http://'.$_SERVER['HTTP_HOST'].'/'.$folder;`
 на
`$config['site_url']='https://'.$_SERVER['HTTP_HOST'].'/'.$folder;`

**Comment by vla7** [comment]
Необходимо сменить "http://" в данных местах на "//" для универсальности.

**Comment by vla7** [comment]
Обновлено. На текущей версии должно работать. https://github.com/vla7/akina/archive/master.zip
