### ISSUE TITLE
как  изменить   файл 

### ISSUE THREAD

**Issue by ruslanishe** [vla7/akina#118]
закинул файлы на хост  при открытие  картинок  по привью  открывается  этот же  хост где лежат картинки  в файле  менял **view_one.tpl**   на Прямая ссылка на картинку  тогда так открывает  а где изменить  в самом файле  этот код   BB-код всех превью+картинок в файле **view_summary.tpl** что бы не было так  же при открывания

**Comment by TerVel76** [comment]
Текст не понятен. Можно посмотреть на ваш проект?

The text is not clear (don't undastand).

**Comment by ruslanishe** [comment]
сылку куда скидывать

**Comment by TerVel76** [comment]
Все работает. Ссылки ведут куда надо. 
Что не так?

**Comment by TerVel76** [comment]
http://interhit.org/img/2017-09/03/mdr92pav9cwjcsmrh2a4lwmsh.png - прямая ссылка
http://interhit.org/?v=2017-09-03_mdr92pav9cwjcsmrh2a4lwmsh.png - ссылка с превью

**Comment by ruslanishe** [comment]
сейчас   покажу   так же на скриншотах

**Comment by ruslanishe** [comment]
[url=http://interhit.org/?v=2017-09-03_gi28fu9opqo0b8n8ngou9ijz3.png][img]http://interhit.org/thumbs/2017-09/03/gi28fu9opqo0b8n8ngou9ijz3.png[/img][/url] [url=http://interhit.org/?v=2017-09-03_jqaw0gl9pi271rf68p96odajt.png][img]http://interhit.org/thumbs/2017-09/03/jqaw0gl9pi271rf68p96odajt.png[/img][/url]  2 скриншота с B-код всех превью+картинок:  а я хотел   что бы эти скриншоты    вставали вот так  [url=http://interhit.org/img/2017-09/03/gi28fu9opqo0b8n8ngou9ijz3.png][img]http://interhit.org/thumbs/2017-09/03/gi28fu9opqo0b8n8ngou9ijz3.png[/img][/url] [url=http://interhit.org/img/2017-09/03/jqaw0gl9pi271rf68p96odajt.png][img]http://interhit.org/thumbs/2017-09/03/jqaw0gl9pi271rf68p96odajt.png[/img]  вот только  как так прописать что бы они были полноразмерные  без  перехода на сайт

**Comment by ruslanishe** [comment]
разобрался я  в данной  проблеме.   нужно было   сделать   так в файле  `$config['view_page']=0; //добавлять к коду изображения с превью ссылку на "Страницу просмотра" 0 - выключено, 1 - включено  поставить   циферку за место   1  поставить  0   и все встало как нужно мне.    спасибо  за отличный хостинг   акина
