### ISSUE TITLE
код  thumb

### ISSUE THREAD

**Issue by ruslanishe** [vla7/akina#119]
приветствую  подскажите мне  если такое можно сделать. код  thumb  что бы ссылки были  в нем  прямые ну по клику  привью.  в двух  файлах  это нужно  изменить  а именно  в  view_one.tpl  и view_summary.tpl   пример   типо должен быть такой.  [thumb] тут ссылка [/thumb]  это  для view_one.tpl и   другая  тоже самая  ну только  в view_summary.tpl  весь код   выделить.  спасибо  за помощь

**Comment by TerVel76** [comment]
$config['view_page']=1; //добавлять к коду изображения с превью ссылку на "Страницу просмотра" 0 - выключено, 1 - включено
//если выключено всегда будет ссылка вести прямо на оригинальную картинку

**Comment by ruslanishe** [comment]
это  не то...   нужно что типо   так [img]https://c.radikal.ru/c38/1805/1b/6137c07c961e.png[/img]   я вот и не могу понять   как  это сделать  в одном именно файле...   прописать    такой код  и что  было именно  в таком окошке  только    ссылки  и что   их  можно  было  выделить  их как  остальные...
