### ISSUE TITLE
Проект живой? Оптимизацию под PHP7 бы...

### ISSUE THREAD

**Issue by PavlovMD** [vla7/akina#123]
Искал для своего сервера фотохостинг. Чисто для себя. Наткнулся на Akina. Отличный хостинг. Проблема только в одном - не оптимизирован под PHP7(4). ПРоект живой или всё?

**Comment by vla7** [comment]
Здравствуйте. Какие именно проблемы возникают на PHP7?

**Comment by PavlovMD** [comment]
Проблемы с графическим отображением и проблемы в файлах index.php и upload.php (остальное пока не изучал).
[http://wolves-bh.ru/akina/img/2020-03/10/max04iqmpxyiyq9dtp0yitn5q.png](url)
[http://wolves-bh.ru/akina/img/2020-03/10/8qspb35tpeh1ukhish5tazr9s.png](url)
В index.php переделал define, а то выскакивала подобная рыжая ошибка
[http://wolves-bh.ru/akina/img/2020-03/10/e3gw9z1drhvjhufvr5uqr242c.png](url)

**Comment by PavlovMD** [comment]
По поводу отработки стилей вопрос решился путем исправления в `config.php` на 46 строке:
с
`$config['site_url']='http://'.$_SERVER['HTTP_HOST'].'/'.$folder;`
на
`$config['site_url']='//'.$_SERVER['HTTP_HOST'].'/'.$folder;`
и в файле `templates/whatsyoursolution/index.tpl` убрал http у ссылки:
`http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js`

А вот ошибка в файле `upload.php` всё еще осталась.

**Comment by vla7** [comment]
Проблемы совместимости с PHP7 исправлены.

**Comment by PavlovMD** [comment]
Благодарю! НО, я хочу оставить еще сообщение. Скачал с офсайта архив с акиной, залил на сервер и перестали подхватываться стили. Хз, в чем проблема.

Решил проверить изменения в файле upload.php. Заметил изменения в регулярном выражении. В итоге заменил строку 14 на 
`preg_match_all ('#(https?://[\w\-]+[\.\w\-]+/((?!https?://)[\w\- ./?%&=])+)#', $_POST['web_uploadfile'], $out);`
в предыдущей сборке и всё заработало прекрасно!

Подведу итог по решению проблем:
1. **HTTPS.** В файле `config.php` в строке 46 `http://` исправить на `https://`. В файле `templates/whatsyoursolution/index.tpl` в строке 8 `http://` исправить на `https://`.
2. **Некорректный код в `upload.php` в строке 14**. Заменить строку 14 на `preg_match_all ('#(https?://[\w\-]+[\.\w\-]+/((?!https?://)[\w\- ./?%&=])+)#', $_POST['web_uploadfile'], $out);`.

vla7, отличный проект. Еще раз благодарю!

**Comment by vla7** [comment]
Эти проблемы уже исправлены в текущей версии. Вы скачали какую-то старую версию. Скажите где именно и по какой ссылке Вы ее скачали?

**Comment by PavlovMD** [comment]
https://github.com/vla7/akina/archive/master.zip
На сайте http://akina-photohost.org внизу справа есть кнопка "Скачай и используй стабильную версию Akina Current"

**Comment by vla7** [comment]
Там уже все исправлено http://akina-photohost.org/demo/img/2020-03/11/wy4epq9tik08bo71g6rg8sz2n.png, значит Вы что-то не то распаковываете или не туда смотрите, куда распаковали.

**Comment by PavlovMD** [comment]
Сейчас скачал в отдельную папку, распаковал и закинул на сервер. Папку даже не открывал. Посмотрите.
https://ph.superstarper.ru
Как посмотрите, отпишитесь тут. Я заменю на предыдущую сборку с исправлениями, которые указал выше и вы снова посмотрите.

**Comment by PavlovMD** [comment]
> Там уже все исправлено http://akina-photohost.org/demo/img/2020-03/11/wy4epq9tik08bo71g6rg8sz2n.png, значит Вы что-то не то распаковываете или не туда смотрите, куда распаковали.

По поводу ссылки: да, я видел эти изменения, но я описал двумя постами выше шаги для решения проблем с вчерашней сборкой. А вот сегодняшняя че-то без стилей работает(

**Comment by vla7** [comment]
Скачал, распаковал, проверил строки https://pastebin.com/raw/DiNfKVxt
У Вас что в этих строках?

**Comment by PavlovMD** [comment]
Вы про эти строки спрашиваете?
http://ph.superstarper.ru/img/2020-03/11/2uc9n0abtlwbqh68ksreuevav.png

http://ph.superstarper.ru/img/2020-03/11/zedelstwamfc38cv384rvgdxh.png

**Comment by vla7** [comment]
Да, проблему с https нашел, скоро исправлю, спасибо.

**Comment by vla7** [comment]
Можно проверять.

**Comment by PavlovMD** [comment]
> Можно проверять.

Перфекто! Проект жив! :-)

Перед тем, как наткнуться на акину, я шерстил инет в поисках фотохостинга. И могу сказать, что ничего нормально вообще не нашел. Гугл предлагал какие-то сайты-фотохостинги, но мне нужен был свой "домашний" фотохостинг. Рад, что всё хорошо закончилось)

Благодарю!

**Comment by vla7** [comment]
Точно с такого же неудачного поиска почти 10 лет назад началось написание данного движка)
