### ISSUE TITLE
PHP 7.4(4) проблема фигурных скобок (заменить на квадратные)

### ISSUE THREAD

**Issue by PavlovMD** [vla7/akina#124]
В версии PHP 7.4(4) использование фигурных скобок считается устаревшим (согласно ворнингам).
При первом запуске akina (в т.ч после перезагрузки веб-сервера) в шапке сайта появляется предупреждение по трём строкам (182, 187, 189) файла function.php. Ворнинги устраняются заменой фигурных скобок в этих строках на квадратные скобки.

Автору респект за продукт!

З.Ы. Случаем не знаешь, какой-нибудь хорошей веб-галереи для сайта? Перепробовал с десяток разных галерей, но все какие-то сложные или просто не очень. Вот акина - проще некуда, мои простые потребности покрывает с головой. Вот и галерею бы такую простую: закинул папку на хостинг, закинул в нее фотки (а не так, что скормил галереи фотки, а она их задублировала под другими именами) и комменты можно настрочить. Я юзаю plex media server, а там фотки не в родном разрешении. Очень напрягает. Поэтому и ищу галерею.

**Comment by vla7** [comment]
>предупреждение по трём строкам (182, 187, 189) файла function.php
Спасибо, пофикшено.

>Случаем не знаешь, какой-нибудь хорошей веб-галереи для сайта
К сожалению, не было потребности, не знакомился с галереями. Возможно будь потребность - написал бы свою)
