### ISSUE TITLE
function.php error "Too few arguments to function resize()"

### ISSUE THREAD

**Issue by PavlovMD** [vla7/akina#125]
При попытке загрузить картинку и уменьшить ее, вылетает ошибка.
275 строка --->  `resize("{$config['working_dir']}$filename", $_POST['width'], $_POST['height']);`
Там вроде как 5 аргументов надо для функции. В начале файла есть строка
`resize("{$config['working_thumb_dir']}$filename", $thumb_width, $thumb_height, $_POST['texttype'],"{$config['working_dir']}$filename");`
но я сам не догнал, как правильно воткнуть аргументы((

**Comment by RealStrannik** [comment]
Как я понял проект мёртв и ответа не будет?

**Comment by vla7** [comment]
> Как я понял проект мёртв и ответа не будет?

Проект скорее жив, чем мертв, но проект бесплатный и автор занимается им в свободное время. 
Ожидайте, постараюсь разобраться в ближайшие дни.

**Comment by vla7** [comment]
Проверьте на актуальной версии https://github.com/vla7/akina/releases/tag/v1.2
Если еще актуально - укажите шаги для воспроизведения проблемы.

**Comment by PavlovMD** [comment]
Захожу в акину, выбираю картинку с разрешением 1024х1024, ставлю галку "Уменьшить изображение", ставлю размер 400х400, жму кнопку "Загрузить", получаю ошибку
![Снимок экрана 2020-08-13 в 11 46 48](https://user-images.githubusercontent.com/32665280/90114699-c4b24000-dd5b-11ea-879f-12ef6284173e.png)

**Comment by vla7** [comment]
Поправил https://github.com/vla7/akina/commit/e555aadf39e2b50fd0e6f3c27cc650faba7aa453
Проверьте
https://github.com/vla7/akina/archive/master.zip

**Comment by PavlovMD** [comment]
При тех же действиях ошибка больше не появляется. Благодарю!)
