### ISSUE TITLE
Сохранять загруженные пользователем изображения

### ISSUE THREAD

**Issue by GoogleCodeExporter** [vla7/akina#23]
```
Сохранять загруженные пользователем 
изображения у него в куках, сделать 
страницу просмотра этих изображений.


```

Original issue reported on code.google.com by `Panop...@gmail.com` on 7 Dec 2011 at 11:57

**Comment by vla7** [comment]
Для реализации потребуется реализовать
- регистрацию
- авторизацию
- восстановление пароля
- страницу просмотра изображений.

Суть данного проекта в минимализме, а не в портале.
