### ISSUE TITLE
Сервис коротких ссылок

### ISSUE THREAD

**Issue by GoogleCodeExporter** [vla7/akina#77]
```
Наверное не плохо было бы добавить сервис 
коротких ссылок для "Прямой ссылки на 
картинку" и "Страница просмотра"
```

Original issue reported on code.google.com by `b2r...@gmail.com` on 29 Jan 2014 at 7:57

**Comment by vla7** [comment]
Считаю мало кому надо. Предлагаю закрыть.

**Comment by NeoMaks** [comment]
А я считаю что надо. Сейчас в моде короткие ссылки. Длинные сильно забивают базу данных ненужным хламом. Вот прикрутить бы короткие ссылки как на TinyURL цены бы движку не было...
