### ISSUE TITLE
Данные о незаконной попытке доступа успешно занесены в лог.'; @fclose($fp); die; } ?>

### ISSUE THREAD

**Issue by GoogleCodeExporter** [vla7/akina#91]
```
1.0.8 версия
Мне пишет 
"Данные о незаконной попытке доступа 
успешно занесены в лог.'; @fclose($fp); die; } ?>"

подскажите как это можно исправить?

```

Original issue reported on code.google.com by `navo...@gmail.com` on 16 Nov 2014 at 3:08

**Comment by TerVel76** [comment]
Это давно поправлено еще в (r65) v1.0.9a Aug 20, 2014
------
 Fix Issue 84 https://code.google.com/p/akina/issues/detail?id=84
