### ISSUE TITLE
Ошибка загрузки

### ISSUE THREAD

**Issue by Yadrik** [vla7/akina#94]
Здравствуйте.
Ошибка!
Ошибка! Максимально допустимый размер загружаемого изображения в php.ini (2M) меньше заданного в настройках фотохостинга (5 МБ) ( стоит в php.ini 756 мб. [ ispmanager 4] . Также поставил права 777 на все папки и файлы но не загружает изоображение на сайт . Как решить проблему ?

**Comment by TerVel76** [comment]
Какая версия Akina ?

**Comment by vla7** [comment]
Где?

25.06.2015 22:49, Vladek aka TerVel пишет:

**Comment by TerVel76** [comment]
У Yadrik , который жалуется на ошибки загрузки.

**Comment by Yadrik** [comment]
Я установил .

**Comment by TerVel76** [comment]
Что именно установили?

**Comment by vla7** [comment]
Проблема еще актуальна?
