### ISSUE TITLE
Дополнение - Обратная связь

### ISSUE THREAD

**Issue by svzart** [vla7/akina#98]
Всем привет. Выкладываю дополнение обратная связь. В данный момент дизайн сделан под шаблон bluestyle . Все стили закинул в файл feedback.static.tpl но кто хочет может перенести в свой css. В файле contacts.php заменить ВАШ@ЕМАИЛ.ru на свой e-mail. Файл contacts.php засунул в папку feedback так как планирую сделать капчу и положить туда же. Кто захочет файл contacts.php бросить в корень или ещё куда-нибудь, то измените пути в feedback.static.tpl на файл contacts.php 
Сам скрипт состоит из двух файлов.
contacts.php  и feedback.static.tpl

ГОТОВОЕ РЕШЕНИЕ МОЖЕТЕ СКАЧАТЬ по ссылке ниже
Загрузите в корень, распакуйте и в файле contacts.php заменить ВАШ@ЕМАИЛ.ru на свой e-mail
По умолчанию путь в архиве ведет на шаблон bluestyle

https://cloud.mail.ru/public/Jfks/hhLyHNZJW

Данное решение не затрагивает ни каких системных файлов и не слетит при обновлении.
ДЕМО не выкладываю так как нет времени на его создание, а свой сайт не хочу светить, так как  заспамите пробуя как работает. Так что извиняйте. Только скриншот. Если кому не лень, то сделайте демку и всем будет хорошо.
![feedback](https://cloud.githubusercontent.com/assets/13207557/8541475/93bc730a-249f-11e5-978a-8e4ab83391ac.jpg)

**Comment by TerVel76** [comment]
Спасибо за код :) добавлю в следующий релиз.

**Comment by MihaylovRA** [comment]
Всё работает. Спасибо! Демо: http://fotohosting.info/?p=feedback

Жду капчу.

**Comment by vla7** [comment]
Вопрос закрыт по сроку давности.
