### ISSUE TITLE
Уменьшение по наибольшей стороне

### ISSUE THREAD

**Issue by seregin118** [vla7/akina#99]
При загрузке картинки на фотохост добавить вариант - уменьшить по наибольшей стороне. В версии скрипта 1.5 можно было проставить значение по высоте и по ширине одновременно. Скрипт ругался, но уменьшал по наибольшей стороне. Сейчас такой вариант не проходит.  Кстати, пропорции изображения не нарушали.

Можно, конечно, добавить ещё один пункт - в зависимости от веса картинки принудительно пересохранять в другом качестве. Но это так, мысли вслух.

Спасибо за внимание.

**Comment by seregin118** [comment]
Можно ещё добавить функционал,  но я даже не знаю о существования такой возможности - автоматически удалять изображения которые не запрашивает около года.

**Comment by TerVel76** [comment]
Предложения хорошие, можно будет учесть в следующих релизах.

А по поводу удаления, это возможно сделать только если есть cron на стороне хостинга.

**Comment by seregin118** [comment]
Спасибо за одобрение.

Что касается второго, то cron есть, но.. Простое удаление по расписанию настроить не так сложно.  Самое главное, это - удаление,  по условию если файл не запрашивали на сторонних сайтах. Я даже  и её представляю реальность реализации моего предложения.
Спасибо ещё раз за вашу работу.

**Comment by TerVel76** [comment]
https://code.google.com/p/akina/issues/detail?id=88#c11

**Comment by seregin118** [comment]
Спасибо.

**Comment by vla7** [comment]
Удаление на уровне php в самом коде реализовывать нет смысла. Удаление может занимать более 30-60 секунд и должно проводиться через крон.
Для маленьких сайтов разве что, но что им удалять, если они маленькие.
Одним словом этого в движке быть не должно.

**Comment by seregin118** [comment]
Благодарю предыдущий линк решил все вопросы относительно этого вопррса
